# This Docker Container provides:
# Port 22 SSH Access, wi no root priv
# Port 8022 Webshell to SSH server (via 127.0.0.1:22)
# letsencrypt cert for domain
# ---------------------------------------------------
# httpd auth einbauen
version: "3"

services:
  sshd:
    hostname: ${HOSTNAME}
    build: 
      context: './sshd/'
      args:
        - SSH_USERNAME=${USER_NAME}
        - SSH_PASSWORD=${USER_PWD}
        - SSH_PUB_KEY=${USER_PUBKEY}
        - HOSTNAME=${HOSTNAME}
    ports:
      - "193.239.21.17:22:22"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./log/:/var/log/

  nginx:
    image: nginx:1.19-alpine
    restart: unless-stopped
    ports:
      - "193.239.21.17:8022:8022"
      - "193.239.21.17:80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www/:/var/www/certbot/
      - ./certbot/conf/:/etc/letsencrypt/
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf/:/etc/letsencrypt/
      - ./certbot/www/:/var/www/certbot/
      - ./log/letsencrypt/:/var/log/letsencrypt/
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
